Adds Hub-spoke implementation to the workshop
mspnp/caf-secure-amp-infra pull request #14
Opened 2021-07-08 02:46 UTC by pabrus

This PR is adding a reference hub-spoke implementation
Includes/depends on the changes defined at https://github.com/mspnp/caf-secure-amp-infra/pull/13.

- Adds Hub-spoke Network Topology with Azure Virtual WAN to ARM template
- Adds Hub-spoke settings into custom UI for portal deployment
- Updates README file

2021-07-08 02:47 UTC, pabrus commented on README.md
> +[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#blade/Microsoft_A
Reminder to change branch back to main before merging

2021-07-08 02:47 UTC, pabrus commented on deploy/caf-secure-deploy.json
> +        "templateRootUri": "https://raw.githubusercontent.com/mspnp/caf-secure-amp-infra/pabrus/hubspoke/deploy/auxiliary/",
Reminder to change branch back to main before merging

2021-07-08 13:00 UTC, ckittel requested changes
Before I review futher, just need to validate something I wasn't expecting.  Maybe something changed in the requirements?

2021-07-08 13:45 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +        },
I understood we wanted to use vWAN. Probably I am mistaken then.
Should I replace it with a regular hub?

2021-07-08 13:51 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +        },
I was like 99% sure we _didn't_ want to use vWAN.  Please check with the product owner to validate.

2021-07-09 13:21 UTC, ckittel requested changes
Looks really good.  Couple small items below.  LMK if you have any questions.  Also if the tracking bit isn't working still, let's talk about what situation causes that to bomb.

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                "allowGatewayTransit": true,
```suggestion
                "allowGatewayTransit": false,
```
Typically only needed in hub to spoke peering, and only to support on-prem VPN Gateway/ER.

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                "allowGatewayTransit": true,
```suggestion
                "allowGatewayTransit": false,
```
Typically only needed in hub to spoke peering, and only to support on-prem VPN Gateway/ER.

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                ],
Are we going to leave subnets out at this point?  That coming later this sprint?  Hubs typically have three, one for gateway, one for FW, one for Azure Bastion.  With NSGs on the Azure Bastion subnet.

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                ]
Would make sense to have a placeholder (default) NSG apply to this subnet.  Doesn't need to be in the PR.

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                ]
One of these spoke vnets will have a App Gateway, which requires a dedicated subnet.  No need to add that subnet in yet, but might be good to start thinking about that wrt how you have the variables/params set up

2021-07-09 13:21 UTC, ckittel commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +            "properties": {
Might be a good question for Dom, but just because we're using a single subscription, doesn't mean we should be using a single resource group for hubs AND spokes I would imagine.  ES keeps hubs in a completely separate subscription, and it might make sense to mirror that by putting regional hubs in a separate resource group.  Can ask Dom if that's worthwhile showing.  Otherwise I'm afraid it's going to look like a bunch of stuff just all smooshed together.

2021-07-09 13:21 UTC, ckittel commented on deploy/caf-secure-deploy.json
> +                "displayName": "Deploy Hub-spoke network topology with Azure Virtual WAN",
```suggestion
                "displayName": "Deploy Hub-spoke network topology",
```

2021-07-09 13:21 UTC, ckittel commented on deploy/caf-secure-deploy.json
> +                "description": "If 'Yes', ARM will deploy DDoS Protection plan. If 'No', it will be skipped"
```suggestion
                "description": "If 'Yes', DDoS Protection plan will be applied to spokes with ingress traffic. If 'No', it will be skipped"
```

2021-07-09 13:21 UTC, ckittel commented on deploy/caf-secure-ui.json
> +                        "label": "Deploy Hub-spoke network topology with Azure Virtual WAN",
```suggestion
                        "label": "Deploy Hub-spoke network topology",
```

2021-07-09 13:21 UTC, ckittel commented on deploy/caf-secure-ui.json
> +                        "toolTip": "If 'Yes', ARM will deploy DDoS Protection plan. If 'No', it will be skipped",
```suggestion
                        "toolTip": "If 'Yes', DDoS Protection plan will be applied to spokes with ingress traffic. If 'No', it will be skipped"
```

2021-07-10 01:44 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                }
I have added DDoS everywhere now, as we don't really know what the real usage for each vnet wil be, it is very hard to undestand where DDos should be applied.

2021-07-10 01:45 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                "allowGatewayTransit": true,
Done

2021-07-10 01:45 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                "allowGatewayTransit": true,
Done

2021-07-10 01:45 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                ],
I have added the subnets, Firewall and Gateway will come in future PR.

2021-07-10 01:45 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +                ]
Added an empty  NSG for each subnet

2021-07-10 01:46 UTC, pabrus commented on deploy/auxiliary/caf-secure-hubSpoke.json
> +            "properties": {
I have separete deployment even more (in smaller files) and created resource groups for hubs and spokes.
Let me know what you think.

2021-07-10 01:46 UTC, pabrus commented on deploy/caf-secure-deploy.json
> +                "displayName": "Deploy Hub-spoke network topology with Azure Virtual WAN",
Done!

2021-07-10 01:46 UTC, pabrus commented on deploy/caf-secure-deploy.json
> +                "description": "If 'Yes', ARM will deploy DDoS Protection plan. If 'No', it will be skipped"
Done!

2021-07-10 01:47 UTC, pabrus commented on deploy/caf-secure-ui.json
> +                        "label": "Deploy Hub-spoke network topology with Azure Virtual WAN",
Done!

2021-07-10 01:47 UTC, pabrus commented on deploy/caf-secure-ui.json
> +                        "toolTip": "If 'Yes', ARM will deploy DDoS Protection plan. If 'No', it will be skipped",
Done!

2021-07-10 01:48 UTC, pabrus commented
@ckittel I think I have tackled most of the  issues. Thanks for the review.

2021-07-10 01:50 UTC, pabrus commented
> Looks really good. Couple small items below. LMK if you have any questions. Also if the tracking bit isn't working still, let's talk about what situation causes that to bomb.

Tracking is not failing anymore 😕 so we should be fine.
The only thing that prevents two consecutive deployments are the "roleAssignments"

2021-07-15 15:48 UTC, ckittel commented on README.md
> +[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#blade/Microsoft_A
set back

2021-07-15 15:48 UTC, ckittel commented on deploy/caf-secure-deploy.json
> +        "templateRootUri": "https://raw.githubusercontent.com/mspnp/caf-secure-amp-infra/pabrus/hubspoke/deploy/auxiliary/",
set back

2021-07-15 15:49 UTC, ckittel approved these changes

2021-07-15 15:53 UTC, merged