Adds application gateway
mspnp/caf-secure-amp-infra pull request #16
Opened 2021-07-10 07:20 UTC by pabrus

This PR is adding Azure Application Gateway to the reference hub-spoke implementation
Depends on https://github.com/mspnp/caf-secure-amp-infra/pull/15

2021-07-15 16:34 UTC, ckittel requested changes
Before I get too far into the review, just want to validate a pretty significant decision to have the hub contain an App Gateway, vs the workload spokes.

2021-07-15 16:34 UTC, ckittel commented on deploy/caf-secure-ui.json
> +                                "toolTip": "Subnet address prefix for the gateway for the hub network",
Not sure this text (or the previous text) makes sense in the context.  What is a "gateway _for the hub network_ mean?"  App Gateways are for spoke networks.

2021-07-15 16:34 UTC, ckittel commented on deploy/caf-secure-ui.json
> +                                "toolTip": "Subnet address prefix for Azure Application Gateway for the hub network",
Not sure this text (or the previous text) makes sense in the context.  What is a "gateway _for the hub network_ mean?"  App Gateways are for spoke networks.

2021-07-15 16:34 UTC, ckittel commented on deploy/caf-secure-ui.json
> +                                "label": "Subnet prefix for the gateway",
"gateway" might be best left as "Azure Application Gateway" to be clearer about what's being deployed.

2021-07-15 16:34 UTC, ckittel commented on deploy/auxiliary/caf-secure-networking-hub.json
> +                            ],
Really surprised to see this in the hub.  Is this guidance from someplace?  Typically an App Gateway is a workload level concern that exists in a spoke.

2021-07-24 03:25 UTC, pabrus commented
@ckittel I have done some changes now. Could you please check it again? Thanks

2021-07-27 22:36 UTC, ckittel commented
Thanks @pabrus -- I'll add this to my review list for tomorrow.

2021-07-28 15:38 UTC, ckittel commented
Just notes from our call (from what I can remember):

* Tooltip saying something like "Availability zones are only available in certain Azure regions." on the Azure region and the items where availability zones are selected.
* Availability zones (1,2,3) are selected by default.
* NSG on Azure Bastion -- no need for config option for this.
* NSG on App GW (80 from internet + required) -- no need for config option for this.
* OWASP 3.2 -- no need for config option for this.
* multiple IPs on FW (at least 2, 3 would be good as well) -- no need for config option for this.

2021-07-29 12:18 UTC, pabrus commented
> * Availability zones (1,2,3) are selected by default.
This one can't be done 😞 defaultValue only allows one option even if the dropdown is set to be multiple.

2021-07-29 12:37 UTC, pabrus commented on README.md
> +[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#blade/Microsoft_A
Update branch before merging

2021-07-29 12:38 UTC, pabrus commented on deploy/caf-secure-deploy.json
> +        "templateRootUri": "https://raw.githubusercontent.com/mspnp/caf-secure-amp-infra/pabrus/appgw/deploy/auxiliary/",
Update branch before merge

2021-07-29 13:11 UTC, ckittel approved these changes
Besides your branch change in the URLs, good to go.  Thanks for making the changes.  Bummer about the multi-select defaults.

2021-07-29 14:10 UTC, merged